'use strict';

// migrations/0001_create_users.js
// Creates the users table.
// Users are auto-created on first successful GitHub OAuth login (FR-AUTH-002).
// Supports soft deletion via deleted_at — deleted users are retained for 30 days
// before permanent removal (DATA-003).
//
// Do NOT edit this file after it has been applied to any database.
// To change the schema, create a new numbered migration.

exports.shorthands = undefined;

exports.up = (pgm) => {
  pgm.createTable('users', {
    id: {
      type: 'serial',
      primaryKey: true,
    },
    github_id: {
      type: 'bigint',
      notNull: true,
      unique: true,
      comment: 'GitHub numeric user ID — stable identifier from the GitHub API',
    },
    github_username: {
      type: 'varchar(255)',
      notNull: true,
      comment: 'GitHub login handle (may change; use github_id as the stable key)',
    },
    email: {
      type: 'varchar(255)',
      comment: 'Primary email from GitHub profile — may be null if user has hidden it',
    },
    role: {
      type: 'varchar(50)',
      notNull: true,
      default: 'intern',
      check: "role IN ('project_manager', 'intern', 'stakeholder', 'compliance_auditor')",
      comment: 'Role assigned to this user — governs capability set in execution/rbac/roles.js',
    },
    created_at: {
      type: 'timestamptz',
      notNull: true,
      default: pgm.func('NOW()'),
    },
    updated_at: {
      type: 'timestamptz',
      notNull: true,
      default: pgm.func('NOW()'),
    },
    deleted_at: {
      type: 'timestamptz',
      comment: 'Set on soft delete. Null means the user is active.',
    },
  });

  pgm.createIndex('users', 'github_id');
  pgm.createIndex('users', 'email');
};

exports.down = (pgm) => {
  pgm.dropTable('users');
};
