'use strict';

// migrations/0002_create_sessions.js
// Creates the sessions table.
// Stores hashed session tokens only — raw tokens are NEVER persisted (FR-AUTH-003).
// Sessions expire after 24 hours of inactivity (config.sessionExpiryHours).
// Cascades on user deletion so sessions are cleaned up automatically.
//
// Do NOT edit this file after it has been applied to any database.
// To change the schema, create a new numbered migration.

exports.shorthands = undefined;

exports.up = (pgm) => {
  pgm.createTable('sessions', {
    id: {
      type: 'serial',
      primaryKey: true,
    },
    user_id: {
      type: 'integer',
      notNull: true,
      references: '"users"(id)',
      onDelete: 'CASCADE',
      comment: 'FK to users.id — session is invalidated if the user is hard-deleted',
    },
    token_hash: {
      type: 'varchar(64)',
      notNull: true,
      unique: true,
      comment: 'SHA-256 hex digest of the raw token — 64 characters',
    },
    created_at: {
      type: 'timestamptz',
      notNull: true,
      default: pgm.func('NOW()'),
    },
    last_active_at: {
      type: 'timestamptz',
      notNull: true,
      default: pgm.func('NOW()'),
      comment: 'Updated on each validated request — used to enforce the inactivity expiry',
    },
    expires_at: {
      type: 'timestamptz',
      notNull: true,
      comment: 'Set at creation as NOW() + sessionExpiryHours. Refreshed to now + sessionExpiryHours on every validated request (rolling inactivity window). Enforced in validateSession.',
    },
  });

  pgm.createIndex('sessions', 'token_hash');
  pgm.createIndex('sessions', ['user_id', 'expires_at']);
};

exports.down = (pgm) => {
  pgm.dropTable('sessions');
};
