'use strict';

// migrations/0003_create_audit_logs.js
// Creates the audit_logs table.
// All application audit events flow through execution/audit/logEvent.js.
// This table is append-only — no UPDATE or DELETE helpers exist anywhere in
// the codebase. The down migration drops the table only as a rollback escape
// hatch; it must never be run against production.
//
// actor_id is VARCHAR, not an FK to users.id, so audit records survive user
// deletion and can represent system events (actor_id = '0').
//
// Do NOT edit this file after it has been applied to any database.
// To change the schema, create a new numbered migration.

exports.shorthands = undefined;

exports.up = (pgm) => {
  pgm.createTable('audit_logs', {
    id: {
      type:       'serial',
      primaryKey: true,
    },
    actor_id: {
      type:    'varchar(255)',
      notNull: true,
      comment: 'ID of the acting user as a string; "0" represents system-generated events',
    },
    action: {
      type:    'varchar(255)',
      notNull: true,
      comment: 'Past-tense dot-namespaced event descriptor (e.g. "user.login")',
    },
    resource_type: {
      type:    'varchar(255)',
      notNull: true,
      comment: 'Entity category affected by the action (e.g. "session", "repo")',
    },
    resource_id: {
      type:    'varchar(255)',
      notNull: true,
      comment: 'Identifier of the specific entity that was affected',
    },
    metadata: {
      type:    'jsonb',
      notNull: true,
      default: pgm.func("'{}'::jsonb"),
      comment: 'Arbitrary key-value context supplied by the caller; defaults to empty object',
    },
    created_at: {
      type:    'timestamptz',
      notNull: true,
      comment: 'Timestamp of the event, supplied by the caller (never defaulted at DB level)',
    },
  });

  // Query patterns supported by these indexes:
  //   - "all events by this user over time"     → actor_id + created_at
  //   - "all events of this type over time"     → action   + created_at
  //   - "full history for this resource"        → resource_type + resource_id
  pgm.createIndex('audit_logs', ['actor_id',     'created_at']);
  pgm.createIndex('audit_logs', ['action',       'created_at']);
  pgm.createIndex('audit_logs', ['resource_type', 'resource_id']);
};

exports.down = (pgm) => {
  pgm.dropTable('audit_logs');
};
