'use strict';

// migrations/0004_add_access_token_to_users.js
// Adds access_token_enc to the users table.
// The GitHub OAuth access token is encrypted at rest with AES-256-GCM via
// execution/crypto/encryptToken.js before being stored here. The raw token
// is never persisted. This column enables background sync jobs (Phase 3) to
// call the GitHub API on behalf of the user without requiring re-authentication.
//
// Do NOT edit this file after it has been applied to any database.
// To change the schema, create a new numbered migration.

exports.shorthands = undefined;

exports.up = (pgm) => {
  pgm.addColumn('users', {
    access_token_enc: {
      type:    'text',
      comment: 'AES-256-GCM encrypted GitHub OAuth access token. Format: iv:tag:ciphertext (all hex). Null until the user completes their first login after this migration.',
    },
  });
};

exports.down = (pgm) => {
  pgm.dropColumn('users', 'access_token_enc');
};
