'use strict';

// migrations/0005_create_repositories.js
// Tracks GitHub repositories a user has linked to RepoPulse.
// github_repo_id is the stable identifier from the GitHub API — github_full_name
// may change when a repo is renamed or transferred.
//
// Do NOT edit this file after it has been applied to any database.
// To change the schema, create a new numbered migration.

exports.shorthands = undefined;

exports.up = (pgm) => {
  pgm.createTable('repositories', {
    id: {
      type:       'serial',
      primaryKey: true,
    },
    user_id: {
      type:       'integer',
      notNull:    true,
      references: '"users"(id)',
      onDelete:   'CASCADE',
      comment:    'Owner of this repository link — FK to users.id',
    },
    github_repo_id: {
      type:    'bigint',
      notNull: true,
      unique:  true,
      comment: 'Stable numeric GitHub repository ID from the API',
    },
    github_full_name: {
      type:    'varchar(512)',
      notNull: true,
      comment: 'owner/repo format — may change on rename or transfer',
    },
    is_active: {
      type:    'boolean',
      notNull: true,
      default: true,
      comment: 'When false the repo is skipped during sync but retained for history',
    },
    linked_at: {
      type:    'timestamptz',
      notNull: true,
      comment: 'When this repository was first linked to RepoPulse',
    },
    last_synced_at: {
      type:    'timestamptz',
      comment: 'Timestamp of the most recent successful sync. Null until first sync.',
    },
  });

  pgm.createIndex('repositories', 'user_id');
  pgm.createIndex('repositories', 'github_repo_id');
};

exports.down = (pgm) => {
  pgm.dropTable('repositories');
};
