'use strict';

// migrations/0006_create_repo_metrics.js
// Immutable snapshot of a repository's GitHub activity metrics at a point in time.
// Each sync run inserts one row per repository — rows are never updated.
// Queries always read the most recent snapshot (MAX snapshot_at or ORDER BY snapshot_at DESC LIMIT 1).
//
// Do NOT edit this file after it has been applied to any database.
// To change the schema, create a new numbered migration.

exports.shorthands = undefined;

exports.up = (pgm) => {
  pgm.createTable('repo_metrics', {
    id: {
      type:       'serial',
      primaryKey: true,
    },
    repo_id: {
      type:       'integer',
      notNull:    true,
      references: '"repositories"(id)',
      onDelete:   'CASCADE',
      comment:    'FK to repositories.id',
    },
    snapshot_at: {
      type:    'timestamptz',
      notNull: true,
      comment: 'Timestamp this snapshot was taken — supplied by the caller, not defaulted',
    },
    commits_7d: {
      type:    'integer',
      notNull: true,
      default: 0,
      comment: 'Number of commits pushed in the 7 days prior to snapshot_at',
    },
    open_prs: {
      type:    'integer',
      notNull: true,
      default: 0,
      comment: 'Total open pull requests at snapshot time',
    },
    stale_prs: {
      type:    'integer',
      notNull: true,
      default: 0,
      comment: 'Open PRs with no activity for more than 7 days',
    },
    open_issues: {
      type:    'integer',
      notNull: true,
      default: 0,
      comment: 'Open issues (excluding pull requests) at snapshot time',
    },
    last_push_at: {
      type:    'timestamptz',
      comment: 'Timestamp of the most recent push to the default branch. Null if never pushed.',
    },
  });

  pgm.createIndex('repo_metrics', ['repo_id', 'snapshot_at']);
};

exports.down = (pgm) => {
  pgm.dropTable('repo_metrics');
};
