'use strict';

// migrations/0007_create_risk_scores.js
// Stores deterministic risk scores computed by execution/risk/scoreRepo.js.
// One row is inserted per repository per sync cycle. Rows are never updated —
// trend is computed at read time from the two most recent rows.
// score range: 0 (healthy) to 100 (critical).
//
// Do NOT edit this file after it has been applied to any database.
// To change the schema, create a new numbered migration.

exports.shorthands = undefined;

exports.up = (pgm) => {
  pgm.createTable('risk_scores', {
    id: {
      type:       'serial',
      primaryKey: true,
    },
    repo_id: {
      type:       'integer',
      notNull:    true,
      references: '"repositories"(id)',
      onDelete:   'CASCADE',
      comment:    'FK to repositories.id',
    },
    snapshot_at: {
      type:    'timestamptz',
      notNull: true,
      comment: 'Timestamp this score was computed — matches the corresponding repo_metrics.snapshot_at',
    },
    score: {
      type:    'integer',
      notNull: true,
      check:   'score >= 0 AND score <= 100',
      comment: '0 = fully healthy, 100 = critical risk',
    },
    label: {
      type:    'varchar(20)',
      notNull: true,
      check:   "label IN ('healthy', 'at-risk', 'critical')",
      comment: 'Human-readable risk bucket derived from score thresholds',
    },
    trend: {
      type:    'varchar(20)',
      notNull: true,
      default: "'stable'",
      check:   "trend IN ('improving', 'stable', 'worsening')",
      comment: 'Direction of change vs the previous score. stable on first snapshot.',
    },
    factors: {
      type:    'jsonb',
      notNull: true,
      default: pgm.func("'[]'::jsonb"),
      comment: 'Array of strings describing which rules contributed to the score',
    },
  });

  pgm.createIndex('risk_scores', ['repo_id', 'snapshot_at']);
};

exports.down = (pgm) => {
  pgm.dropTable('risk_scores');
};
