'use strict';

// migrations/0008_add_ci_status_to_repo_metrics.js
// Adds ci_status to repo_metrics so each sync snapshot captures the
// GitHub Actions pipeline health at that point in time.
// Valid values: 'passing' | 'failing' | 'unknown'
//
// Do NOT edit this file after it has been applied to any database.
// To change the schema, create a new numbered migration.

exports.shorthands = undefined;

exports.up = (pgm) => {
  pgm.addColumn('repo_metrics', {
    ci_status: {
      type:    'varchar(16)',
      notNull: true,
      default: 'unknown',
      comment: "Latest CI pipeline health: 'passing' | 'failing' | 'unknown'",
    },
  });
};

exports.down = (pgm) => {
  pgm.dropColumn('repo_metrics', 'ci_status');
};
