'use strict';

// migrations/0009_add_release_info_to_repo_metrics.js
// Adds release-activity columns to repo_metrics so each sync snapshot captures
// the latest GitHub Release at that point in time.
//
// latest_release_name         — tag_name of the most recent release; null if none or unknown
// latest_release_published_at — published_at timestamp; null if none or unknown
// release_status              — 'healthy' | 'stale' | 'none' | 'unknown'
//
// Do NOT edit this file after it has been applied to any database.
// To change the schema, create a new numbered migration.

exports.shorthands = undefined;

exports.up = (pgm) => {
  pgm.addColumn('repo_metrics', {
    latest_release_name: {
      type:    'varchar(255)',
      notNull: false,
      comment: 'Tag name of the most recent GitHub Release; null when none exists or API unavailable',
    },
    latest_release_published_at: {
      type:    'timestamptz',
      notNull: false,
      comment: 'published_at timestamp of the most recent GitHub Release; null when none exists or API unavailable',
    },
    release_status: {
      type:    'varchar(16)',
      notNull: true,
      default: 'unknown',
      comment: "Release cadence health: 'healthy' | 'stale' | 'none' | 'unknown'",
    },
  });
};

exports.down = (pgm) => {
  pgm.dropColumn('repo_metrics', 'release_status');
  pgm.dropColumn('repo_metrics', 'latest_release_published_at');
  pgm.dropColumn('repo_metrics', 'latest_release_name');
};
