'use strict';

// migrations/0010_add_contributor_info_to_repo_metrics.js
// Adds contributor-activity columns to repo_metrics so each sync snapshot
// captures contributor health at that point in time.
//
// active_contributor_count    — number of contributors with at least one commit;
//                               null when the API is unavailable
// top_contributor_percentage  — share of total commits owned by the top contributor
//                               (0-100, 1 decimal place); null when unknown or abandoned
// contributor_status          — 'healthy' | 'low_activity' | 'bus_factor_risk' |
//                               'abandoned' | 'unknown'
//
// Do NOT edit this file after it has been applied to any database.
// To change the schema, create a new numbered migration.

exports.shorthands = undefined;

exports.up = (pgm) => {
  pgm.addColumn('repo_metrics', {
    active_contributor_count: {
      type:    'integer',
      notNull: false,
      comment: 'Number of contributors with at least one commit; null when API unavailable',
    },
    top_contributor_percentage: {
      type:    'numeric(5,2)',
      notNull: false,
      comment: "Top contributor's share of total commits (0-100, 1 dp); null when unknown or abandoned",
    },
    contributor_status: {
      type:    'varchar(20)',
      notNull: true,
      default: 'unknown',
      comment: "'healthy' | 'low_activity' | 'bus_factor_risk' | 'abandoned' | 'unknown'",
    },
  });
};

exports.down = (pgm) => {
  pgm.dropColumn('repo_metrics', 'contributor_status');
  pgm.dropColumn('repo_metrics', 'top_contributor_percentage');
  pgm.dropColumn('repo_metrics', 'active_contributor_count');
};
