'use strict';

// migrations/0011_create_repo_pr_metrics.js
// Stores PR operational telemetry collected by execution/github/fetchPullRequestHealth.js.
// One row is inserted per repository per sync cycle. Rows are never updated.
// Designed for solo-maintainer portfolios: no reviewer-diversity or review-count columns.
//
// pr_telemetry_status:
//   'active'  — PRs exist and telemetry was collected
//   'none'    — repo has no PR history (valid for new/inactive repos)
//   'unknown' — GitHub API was unavailable or returned an unreadable response
//
// Do NOT edit this file after it has been applied to any database.
// To change the schema, create a new numbered migration.

exports.shorthands = undefined;

exports.up = (pgm) => {
  pgm.createTable('repo_pr_metrics', {
    id: {
      type:       'serial',
      primaryKey: true,
    },
    repo_id: {
      type:       'integer',
      notNull:    true,
      references: '"repositories"(id)',
      onDelete:   'CASCADE',
      comment:    'FK to repositories.id',
    },
    snapshot_at: {
      type:    'timestamptz',
      notNull: true,
      comment: 'Timestamp this telemetry snapshot was captured — matches the sync cycle now',
    },
    open_pr_count: {
      type:    'integer',
      notNull: false,
      comment: 'Number of currently open PRs; null when telemetry is unknown',
    },
    merged_pr_count_30d: {
      type:    'integer',
      notNull: false,
      comment: 'PRs merged in the last 30 days; null when unknown',
    },
    stale_pr_count: {
      type:    'integer',
      notNull: false,
      comment: 'Open PRs older than 7 days but not yet abandoned (> 30 d); null when unknown',
    },
    avg_merge_latency_hours: {
      type:    'numeric(8,1)',
      notNull: false,
      comment: 'Average hours from PR creation to merge over 30-day window; null when no merged PRs',
    },
    failed_check_pr_count: {
      type:    'integer',
      notNull: false,
      comment: 'Open PRs with at least one failed or timed-out check run; null when unknown',
    },
    avg_pr_size: {
      type:    'integer',
      notNull: false,
      comment: 'Mean additions + deletions across open and recently-merged PRs; null when no size data',
    },
    throughput_30d: {
      type:    'numeric(6,1)',
      notNull: false,
      comment: 'Merged PRs per week over the 30-day window; null when unknown',
    },
    abandoned_pr_count: {
      type:    'integer',
      notNull: false,
      comment: 'Open PRs older than 30 days; null when unknown',
    },
    oldest_open_pr_age_days: {
      type:    'numeric(8,1)',
      notNull: false,
      comment: 'Age in days of the oldest currently open PR; null when no open PRs',
    },
    pr_telemetry_status: {
      type:    'varchar(10)',
      notNull: true,
      default: "'unknown'",
      check:   "pr_telemetry_status IN ('active', 'none', 'unknown')",
      comment: "'active' | 'none' | 'unknown'",
    },
    created_at: {
      type:    'timestamptz',
      notNull: true,
      default: pgm.func('NOW()'),
      comment: 'Row-creation timestamp (wall clock, not the sync cycle time)',
    },
  });

  pgm.createIndex('repo_pr_metrics', ['repo_id', 'snapshot_at']);
};

exports.down = (pgm) => {
  pgm.dropTable('repo_pr_metrics');
};
