'use strict';

// migrations/0012_create_repo_architecture_snapshots.js
// Persists architecture intelligence snapshots produced by the GET /api/repos/:id/architecture
// route. One row is inserted per successful live analysis. Rows are never updated — this
// insert-only history enables future architecture drift analytics.
//
// source values:
//   'github' — snapshot was built from GitHub file tree (current only value in v1)
//
// Do NOT edit this file after it has been applied to any database.
// To change the schema, create a new numbered migration.

exports.shorthands = undefined;

exports.up = (pgm) => {
  pgm.createTable('repo_architecture_snapshots', {
    id: {
      type:       'bigserial',
      primaryKey: true,
    },
    repo_id: {
      type:       'integer',
      notNull:    true,
      references: '"repositories"(id)',
      onDelete:   'CASCADE',
    },
    snapshot: {
      type:    'jsonb',
      notNull: true,
      check:   "jsonb_typeof(snapshot) = 'object'",
    },
    snapshot_at: {
      type:    'timestamptz',
      notNull: true,
      default: pgm.func('NOW()'),
    },
    source: {
      type:    'text',
      notNull: true,
      default: "'github'",
    },
    created_at: {
      type:    'timestamptz',
      notNull: true,
      default: pgm.func('NOW()'),
    },
  });

  pgm.sql(`
    CREATE INDEX repo_architecture_snapshots_repo_id_snapshot_at_idx
      ON repo_architecture_snapshots (repo_id, snapshot_at DESC)
  `);
};

exports.down = (pgm) => {
  pgm.dropTable('repo_architecture_snapshots');
};
