'use strict';

// migrations/0013_create_notifications.js
// Creates the notifications table for FR-008 in-app notification channel.
//
// One row is written per user per alert condition (Option B — per-user ownership).
// user_id is NOT NULL and FK to users(id). Notifications are removed if the user
// is hard-deleted (ON DELETE CASCADE). Soft-deleted users retain their rows.
//
// status lifecycle:
//   CREATED  — row written by writeNotification.js; not yet delivered
//   QUEUED   — reserved for future queue-backed dispatch
//   SENT     — delivery confirmed (email/Slack also fired); in-app visible
//   FAILED   — delivery attempt failed
//   READ     — user dismissed/opened the notification via PATCH /api/notifications/:id/read
//   EXPIRED  — retention window elapsed; set by a future cleanup job
//
// dedupe_key:
//   Format: '<alertState>:<trend>'  e.g. 'Critical:Worsening'
//   Uniqueness is enforced per user via the partial unique index
//   notifications_user_dedupe_key_uidx on (user_id, dedupe_key) WHERE dedupe_key IS NOT NULL.
//   writeNotification.js uses ON CONFLICT DO NOTHING so duplicate inserts are silently
//   dropped at the DB layer. The process-lifetime _sent Set in sendAlert.js is a faster
//   in-memory gate; this index is the persistent safety net across process restarts.
//
// project_id is intentionally absent — no projects table exists yet.
//   Add a FK in a future migration once a projects table is created.
//
// id uses serial (integer) to match the integer PK convention used by all other
//   tables in this repository. The spec says UUID but the implementation uses serial
//   throughout; diverging here would break FK type consistency.
//
// expires_at is set to NOW() + 90 days by writeNotification.js.
//   A future cleanup job will set status = 'EXPIRED' for elapsed rows.
//
// Do NOT edit this file after it has been applied to any database.
// To change the schema, create a new numbered migration.

exports.shorthands = undefined;

exports.up = (pgm) => {
  pgm.createTable('notifications', {
    id: {
      type:       'serial',
      primaryKey: true,
    },
    user_id: {
      type:       'integer',
      notNull:    true,
      references: '"users"(id)',
      onDelete:   'CASCADE',
      comment:    'FK to users.id — notification is removed if the user is hard-deleted',
    },
    type: {
      type:    'varchar(100)',
      notNull: true,
      comment: 'Notification category. Initial value: "portfolio_alert". No check constraint — extensible for future types.',
    },
    priority: {
      type:    'varchar(50)',
      notNull: true,
      check:   "priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
      comment: 'Alert severity. Derived from alertState/trend in writeNotification.js. Critical→CRITICAL, Worsening→HIGH, else MEDIUM.',
    },
    title: {
      type:    'varchar(255)',
      notNull: true,
      comment: 'Short human-readable heading, e.g. "[RepoPulse] Critical Alert — Worsening trend"',
    },
    body: {
      type:    'text',
      notNull: true,
      comment: 'Full alert detail text (alertState, trend, riskScore, atRisk count)',
    },
    status: {
      type:    'varchar(50)',
      notNull: true,
      default: "'CREATED'",
      check:   "status IN ('CREATED', 'QUEUED', 'SENT', 'FAILED', 'READ', 'EXPIRED')",
      comment: 'Lifecycle state. Defaults to CREATED on insert. Set to READ by PATCH /api/notifications/:id/read.',
    },
    dedupe_key: {
      type:    'varchar(255)',
      comment: 'Deduplication token (alertState:trend). Partial unique index on (user_id, dedupe_key) prevents duplicate rows per user per condition.',
    },
    created_at: {
      type:    'timestamptz',
      notNull: true,
      default: pgm.func('NOW()'),
      comment: 'Row creation timestamp (UTC)',
    },
    sent_at: {
      type:    'timestamptz',
      comment: 'Set when the notification is dispatched to the user. Null until then.',
    },
    read_at: {
      type:    'timestamptz',
      comment: 'Set when the user marks the notification read. Null until then.',
    },
    expires_at: {
      type:    'timestamptz',
      comment: 'Set to NOW() + 90 days by writeNotification.js. A future cleanup job sets status=EXPIRED for elapsed rows.',
    },
  });

  // Primary read path: all notifications for this user, newest first.
  // Covers: SELECT ... WHERE user_id = $1 ORDER BY created_at DESC LIMIT N
  pgm.sql(`
    CREATE INDEX notifications_user_id_created_at_idx
      ON notifications (user_id, created_at DESC)
  `);

  // Badge count path: unread notification count for this user.
  // Covers: SELECT COUNT(*) WHERE user_id = $1 AND status NOT IN ('READ', 'EXPIRED')
  pgm.sql(`
    CREATE INDEX notifications_user_id_status_idx
      ON notifications (user_id, status)
  `);

  // Dedup key lookup: partial index mirrors the partial unique constraint below.
  // Only rows with a non-null dedupe_key are indexed.
  pgm.sql(`
    CREATE INDEX notifications_dedupe_key_idx
      ON notifications (dedupe_key)
      WHERE dedupe_key IS NOT NULL
  `);

  // Per-user deduplication constraint.
  // One row per user per dedupe_key. Named so writeNotification.js can reference it
  // explicitly in ON CONFLICT ON CONSTRAINT notifications_user_dedupe_key_uidx DO NOTHING.
  pgm.sql(`
    CREATE UNIQUE INDEX notifications_user_dedupe_key_uidx
      ON notifications (user_id, dedupe_key)
      WHERE dedupe_key IS NOT NULL
  `);
};

exports.down = (pgm) => {
  pgm.dropTable('notifications');
};
