'use strict';

// migrations/0014_add_project_status_to_repositories.js
// Adds project_status to repositories for FR-009 project status filtering.
//
// Default is 'active' so all existing rows satisfy the NOT NULL constraint
// without a data migration. Allowed values match the FR-009 filter vocabulary.
//
// Do NOT edit this file after it has been applied to any database.
// To change the schema, create a new numbered migration.

exports.shorthands = undefined;

exports.up = (pgm) => {
  pgm.addColumn('repositories', {
    project_status: {
      type:    'varchar(20)',
      notNull: true,
      default: "active",
      check:   "project_status IN ('active', 'inactive', 'archived', 'unknown')",
      comment: 'Project lifecycle status — used by the FR-009 ?projectStatus= filter',
    },
  });
};

exports.down = (pgm) => {
  pgm.dropColumn('repositories', 'project_status');
};
